# url: "http://coastalforestmerlinproject.org" 
url: "https://miketitus.github.io" 
baseurl: "" # the subpath of your site, e.g. /blog
title: "CFMP" 
description: "Education and Research"
remote_theme: just-the-docs/just-the-docs
