# url: "http://coastalforestmerlinproject.org" 
url: "https://miketitus.github.io" 
baseurl: "" # the subpath of your site, e.g. /blog
title: "CFMP" 
description: "Education and Research"
# remote_theme: just-the-docs/just-the-docs
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
